### PR TITLE
Added a repository mirror for cloud builds.

### PR DESCRIPTION
**Pull request by odisseus**

### CODE REVIEW

**Comment by propensive** [comment]
Some of the changes in here look good, though obviously it's not working yet. (I'm not sure I understand why, though...)

**Comment by odisseus** [comment]
The compilation error is caused by the switch to the new version of Coursier. As to why the Google's mirror isn't used, I still have to investigate that.

**Comment by propensive** [comment]
Is this ready to merge, now that it's passing again?

**Comment by odisseus** [comment]
Merging this PR won't break anything, but the Google mirror still isn't used for some reason.

**Review by propensive — APPROVED** [review]

**Pull request merged**
