### PR TITLE
Simplified interface for granting permissions

### PR DESCRIPTION
**Pull request by odisseus**
This pull request resolves the issue #512.

### CODE REVIEW

**Review by propensive — COMMENTED** [review]
Is it currently possible to add a permission using its full-length hash (i.e. the one that gets printed) rather than the short version of the hash?

**Comment by odisseus** [comment]
Nope

**Comment by propensive** [comment]
Ok, we can add this in a separate PR. This one looks good, thank you! Once CI goes green, of course.

**Comment by odisseus** [comment]
I think that's a serious issue, and I'm going to try to fix it.

**Pull request merged**
