### PR TITLE
Use `procname.c` to set the process name to `fury`

### PR DESCRIPTION
**Pull request by propensive**
Also, do C compilation during install, not during package.

### CODE REVIEW

**Comment by propensive** [comment]
This makes `killall fury` work, when necessary.

**Comment by odisseus** [comment]
On my computer it works even better than expected:
```
$ jps -l
6596 bloop.Server
6468 com.facebook.nailgun.NGServer
6711 sun.tools.jps.Jps
$ killall fury
$ jps -l
6749 sun.tools.jps.Jps
```

**Review by odisseus — CHANGES_REQUESTED** [review]
The C compilation doesn't work on Mac OS:
```
dist/install.sh 

# ...

/Users/user919720/.fury/bin/procname.c:1:10: fatal error: 'sys/prctl.h' file not found
#include <sys/prctl.h>
         ^~~~~~~~~~~~~
1 error generated.
 * Native Nailgun client compilation failed
 * Python Nailgun client will be used
```

**Comment by propensive** [comment]
I think the compilation failure is fine. It has an error, but should gracefully degrade to the old behavior. I'll send all output to `/dev/null` though.

**Pull request merged**
