### PR TITLE
Preload layers before building

### PR DESCRIPTION
**Pull request by odisseus**
This pull request is related to the issue #1197.

### CODE REVIEW

**Review by propensive — CHANGES_REQUESTED** [review]
I think those `zip` commands will be slow. Each one will rewrite the whole 45MB file.

The problem, I think, is that for some reason, these files are not being filtered out. I'm not sure why because there's a condition which checks whether `META-INF` occurs in the entry name which should forbid it from being included in the fat JAR.

**Comment by odisseus** [comment]
I don't think these commands are going to be slow. Each one takes less than a second on my computer. For comparison, unzipping the entire archive takes about 10 seconds.

**Comment by odisseus** [comment]
I have modified the layer definition so thar the repo at `gh:propensive/fury` points to the master branch, commit d7e7d44. This fixed the compilation errors.

Also, the spurious files in META-INF seem to have gone, so I removed the workaround to delete them.

**Comment by propensive** [comment]
Ah, that explains everything then. It was pointing to the wrong version...

**Comment by propensive** [comment]
We even got 8 integration tests to pass! I'll do some work on fixing the rest.

**Review by propensive — APPROVED** [review]

**Pull request merged**
