### PR TITLE
Implemented recursive search for layer.fury till the filesystem boundary

### LINKED ISSUE #266: recursively search parent directories to find `layer.fury`, like `git`
If there is not a `layer.fury` file in the current directory, Fury should search up the tree to see if `fury` commands are being run from within a subdirectory of a Fury project, and choose the ancestor directory which contains `layer.fury` as the base.

### PR DESCRIPTION
**Pull request by odisseus**
This fixes #266.

### CODE REVIEW

**Review by propensive — CHANGES_REQUESTED** [review]
I think I would like to see only a single `Layout` instance visible in all of the for comprehensions, and I'd like `cli.layout` to be changed to always return the main layout, not the "inner" one. Instead of having just the value `pwd` inside of `Layout`, could we have `pwd` (which is the directory `fury` is executed from) and a new value called `base` which is the directory containing the file `layer.fury`?

**Comment by odisseus** [comment]
What about the case when the main layout doesn't exist yet? E. g. running `fury layer init` in an empty directory.

**Comment by propensive** [comment]
I can't check this now, because I'm having some problems with Bloop... it's refusing to compile anything.... I will take another look in the morning.

**Comment by propensive** [comment]
Sorry this took me so long, @odisseus!

**Pull request merged**
