### PR TITLE
Shuffled `fury bsp` command a little more.

### PR DESCRIPTION
**Pull request by odisseus**

### CODE REVIEW

**Review by propensive — CHANGES_REQUESTED** [review]
Can you change `which fury` to `command -v fury`? The latter is POSIX-compliant.

**Review by propensive — CHANGES_REQUESTED** [review]
Can you change `which fury` to `command -v fury`, so that it's POSIX-compliant?

**Comment by propensive** [comment]
Ok, airport wifi *was* working after all. Now you have two reviews! ;)

**Comment by odisseus** [comment]
Changes done

**Review by propensive — APPROVED** [review]

**Pull request merged**
