### PR TITLE
tempoary hacky bash completion script

### PR DESCRIPTION
**Pull request by coconutpalm**
Here's a completion script for Bash that just reformats the zsh completion output.  It's hacky but it works.  :-)

### CODE REVIEW

**Comment by propensive** [comment]
Thank you! That looks like a great stop-gap until I can implement the new version. But why did you close it? ;)

**Comment by coconutpalm** [comment]
Signing the committer agreement requires getting my company's legal department involved.  And lawyers...

But feel free to use the ideas and write your own.. :-)

**Comment by coconutpalm** [comment]
That said, I love Fury's idea and think it could save my company's teams a lot of work.  Dependencies bite us all the time.  Maybe in the future...

**Comment by propensive** [comment]
Ah, I see. :( Depending on how I get on with some of the ideas I have planned for Exoskeleton (which is looking quite hopeful as a full `bash`/`zsh`/`fish` completion system, but isn't ready yet), I may seek inspiration for a hack like yours. Sorry that the CLA made it awkward this time, though...

**Pull request closed without merging**
