### PR TITLE
Don't perform expansion on the arguments with which Nailgun is invoked

### LINKED ISSUE #774: Special symbols are processed by the shell twice if Nailgun is used
## Steps to reproduce
```
$ set -o noglob
$ fury permission require -C java.util.PropertyPermission -T * -A 'read,write'
54bb16098c4d5d4efcbc86a4f7c00b9976dce7a038ca719ea693bfd1a50bf966
$ fury standalone permission require -C java.util.PropertyPermission -T * -A 'read,write'
2614b50c9de54c3c2fb2160fd103c3c3bb7838a20ac665e84fa55e3eee0a1f8d
```
```
$ fury permission list
~/devel/virtus_fury/beholder/test
HASH  CLASS                         TARGET     ACTION    
261   java.util.PropertyPermission  *          read,write
54b   java.util.PropertyPermission  README.md  read,write
```
**Expected result:** the same permission is created twice, the hashes are the same
**Actual result:** two different permissions are added, the hashes are different

### PR DESCRIPTION
**Pull request by odisseus**
Fixes #774.

### CODE REVIEW

**Review by propensive — APPROVED** [review]

**Comment by propensive** [comment]
Can we close this?

**Comment by odisseus** [comment]
I'm working on this pull request at the moment. It seems that the Nailgun server processes ANSI escape codes differently than plain Java.

**Review by propensive — APPROVED** [review]
You could maybe improve the tests slightly by not having them compile anything, e.g.

```
fury project update -D '*'
fury project list
# etc
```

**Comment by propensive** [comment]
It looks like the `check` file for `app-inputs` was actually wrong, and you've fixed a bug. So, run the tests locally, and copy the `test/tmp/app-inputs.log` file to `test/passing/app-inputs/check`, then this is ready to merge!

**Review by propensive — APPROVED** [review]

**Pull request merged**
